# jhu_software_concepts/.readthedocs.yaml
version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.13"

sphinx:
  # point RTD at your module_4 Sphinx conf.py
  configuration: module_4/docs/source/conf.py

python:
  version: 3.10
  install:
    # 1) install your docs/build deps
    - pip install -r module_4/requirements.txt
    # 2) install your module so `import src.pizza` works
    - pip install module_4/
